# Generated by Django 3.2.8 on 2022-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user_profile/default_photo.png', upload_to='user_profile'),
        ),
    ]
