# Generated by Django 3.2.8 on 2022-11-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', upload_to='user_profile', verbose_name='Image'),
        ),
    ]
