# Generated by Django 3.2.8 on 2022-11-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer_id',
        ),
    ]
