# Generated by Django 4.1 on 2022-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False, verbose_name='Category ID')),
                ('category_name', models.CharField(db_column='CategoryName', db_index=True, help_text='format: required,max-100', max_length=100, verbose_name='Category name')),
                ('description', models.TextField(db_column='Description', help_text='format: required,max-150', max_length=150, verbose_name='Description')),
                ('image', models.ImageField(blank=True, db_column='Image', null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
