# Generated by Django 4.1 on 2022-08-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False, verbose_name='Category ID')),
                ('category_name', models.CharField(db_column='CategoryName', db_index=True, max_length=15, verbose_name='Category name')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='Description')),
                ('image', models.BinaryField(blank=True, db_column='Image', null=True, verbose_name='Image')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
