# Generated by Django 4.1 on 2022-08-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_column='CategoryName', db_index=True, help_text='format: required. Max_length: 100', max_length=100, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(db_column='Description', help_text='format: required. Max_length: 150', max_length=150, verbose_name='Description'),
        ),
    ]
