# Generated by Django 4.1 on 2022-08-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(db_column='SupplierID', primary_key=True, serialize=False, verbose_name='Supplier ID')),
                ('company_name', models.CharField(db_column='CompanyName', max_length=40, verbose_name='Company name')),
                ('contact_name', models.CharField(db_column='ContactName', max_length=30, verbose_name='Contact name')),
                ('contact_title', models.CharField(db_column='ContactTitle', max_length=30, verbose_name='Contact title')),
                ('address', models.CharField(db_column='Address', max_length=60, verbose_name='Address')),
                ('city', models.CharField(db_column='City', max_length=15, verbose_name='City')),
                ('region', models.CharField(db_column='Region', max_length=15, verbose_name='Region')),
                ('postal_code', models.CharField(db_column='PostalCode', max_length=10, verbose_name='Postal code')),
                ('country', models.CharField(db_column='Country', max_length=15, verbose_name='Country')),
                ('phone', models.CharField(db_column='Phone', max_length=24, verbose_name='Phone')),
                ('fax', models.CharField(db_column='Fax', max_length=24, verbose_name='Fax')),
                ('homepage', models.TextField(blank=True, db_column='HomePage', null=True, verbose_name='HomePage')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
            },
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='ProductID', primary_key=True, serialize=False, verbose_name='Product ID')),
                ('product_name', models.CharField(db_column='ProductName', db_index=True, help_text='format: required. max_length: 100', max_length=100, verbose_name='Product name')),
                ('description', models.TextField(db_column='Description', help_text='format: required, max_length: 255', max_length=255, verbose_name='Description')),
                ('quantity_per_unit', models.CharField(blank=True, db_column='QuantityPerUnit', max_length=20, verbose_name='Quantity per Unit')),
                ('unit_price', models.DecimalField(blank=True, db_column='UnitPrice', decimal_places=4, max_digits=19, null=True, verbose_name='Unit price')),
                ('units_in_stock', models.SmallIntegerField(blank=True, db_column='UnitsInStock', null=True, verbose_name='Units in Stock')),
                ('units_on_order', models.SmallIntegerField(blank=True, db_column='UnitsOnOrder', null=True, verbose_name='Units on Order')),
                ('reorder_level', models.SmallIntegerField(blank=True, db_column='ReorderLevel', null=True, verbose_name='Reorder level')),
                ('discontinued', models.IntegerField(db_column='Discontinued', verbose_name='Discontinued')),
                ('category_id', models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('supplier_id', models.ForeignKey(blank=True, db_column='SupplierID', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
