version: "3.9"
services:
  db:
    image: postgres:14
    container_name: fxecommerce
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

# pgadmin container setup
# pgadmin:
#   container_name: fx-pgadmin4
#   image: dpage/pgadmin4
#   restart: always

# environment:
#   PGADMIN_DEFAULT_EMAIL: admin@dbadmin.com
#   PGADMIN_DEFAULT_PASSWORD: adminpass123
# ports:
#   - "5050:80"





