# Generated by Django 3.2.8 on 2023-04-12 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='OrderID', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_column='EmployeeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ManyToManyField(blank=True, through='inventory.OrderDetails', to='inventory.Product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_via',
            field=models.ForeignKey(blank=True, db_column='ShipVia', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.shipper'),
        ),
        migrations.AddField(
            model_name='employeeterritory',
            name='employee_id',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='employeeterritory',
            name='territory_id',
            field=models.ForeignKey(db_column='TerritoryID', on_delete=django.db.models.deletion.CASCADE, to='inventory.territory'),
        ),
        migrations.AddField(
            model_name='customercustomerdemo',
            name='customer_id',
            field=models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='customercustomerdemo',
            name='customer_type_id',
            field=models.ForeignKey(db_column='CustomerTypeID', on_delete=django.db.models.deletion.CASCADE, to='inventory.customerdemographics'),
        ),
    ]
