# Generated by Django 3.2.8 on 2022-12-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_column='EmployeeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ManyToManyField(blank=True, through='inventory.OrderDetails', to='inventory.Product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_via',
            field=models.ForeignKey(blank=True, db_column='ShipVia', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.shipper'),
        ),
        migrations.AddField(
            model_name='employeeterritory',
            name='employee_id',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='inventory.employee'),
        ),
        migrations.AddField(
            model_name='employeeterritory',
            name='territory_id',
            field=models.ForeignKey(db_column='TerritoryID', on_delete=django.db.models.deletion.CASCADE, to='inventory.territory'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reports_to',
            field=models.ForeignKey(blank=True, db_column='ReportsTo', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='territories',
            field=models.ManyToManyField(blank=True, through='inventory.EmployeeTerritory', to='inventory.Territory', verbose_name='Territories'),
        ),
        migrations.AddField(
            model_name='customercustomerdemo',
            name='customer_id',
            field=models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='customercustomerdemo',
            name='customer_type_id',
            field=models.ForeignKey(db_column='CustomerTypeID', on_delete=django.db.models.deletion.CASCADE, to='inventory.customerdemographics'),
        ),
    ]
