# Generated by Django 3.2.8 on 2023-01-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, db_column='Photo', upload_to='employee/', verbose_name='Photo'),
        ),
    ]
