# Generated by Django 3.2.8 on 2023-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', upload_to='category/', verbose_name='Image'),
        ),
    ]
